app/routes/auth.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from werkzeug.security import generate_password_hash, check_password_hash
from models.user_models import Users
from db import db
from flask_login import login_user, logout_user, login_required


auth = Blueprint('auth', __name__)

@auth.route('/login', methods=["POST", "GET"])
def login():
        if request.method == 'POST':
            password = request.form['password']
            remember = True if request.form.get('remember') else False
            user = Users.query.filter(Users.email == request.form['email']).first()
            
            if user and check_password_hash(user.password, password): 
                login_user(user, remember=remember)   
                return redirect(url_for('main.profile'))
            else:
                flash('Please check your login details and try again.')
                return render_template('login.html')  
        else:    
            return render_template('login.html')


@auth.route('/signup', methods=["POST", "GET"])
def signup():
    if request.method == 'POST':
        count = Users.query.filter(Users.email == request.form['email']).count()
        if count == 0:
            
            
            n = Users()
            n.name = request.form['name']
            n.email = request.form['email']
            password = request.form['password']
            n.password = generate_password_hash(password, method='sha256')
            
            try:
                db.session.add(n)
                db.session.commit()
                   
                return redirect(url_for('auth.login'))
            except:
                return render_template('signup.html')
                
        else:
            flash('Email address already exists')
            return render_template('signup.html')      
    else:
        return render_template('signup.html')
    
    
    
@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('song.songs'))

app/routes/book.py
from flask import Blueprint,  render_template
from models.book_models import Book
from db import db



book = Blueprint('book', __name__)


@book.route('/books')
def books():
    books = Book.query.all()
    return render_template('books.html', books=books)

@book.route('/book_detail/<int:id>')
def book_detail(id):
    book = Book.query.get(id)
    return render_template('book.html', book=book)
    

app/routes/clinic.py
from flask import Blueprint,  render_template, request, redirect
from models.clinic_models import Patient
from db import db


clinic = Blueprint('clinic', __name__)


@clinic.route('/clinics')
def clinics():
    patients = Patient.query.all()
    return render_template('clinics.html', patients=patients)


@clinic.route('/clinic_add', methods=['GET', 'POST'])
def clinic_add():
    if request.method == 'POST':
        name = request.form['name']
        details = request.form['details']
        weight = float(request.form['weight'])
        age = float(request.form['age'])
        owner_name = request.form['owner_name']
        patient = Patient(name=name, details=details, weight=weight, age=age, owner_name=owner_name)
        db.session.add(patient)
        db.session.commit()
        return redirect('/clinics')
    return render_template('clinic_add.html')


@clinic.route('/clinic/edit/<int:id>', methods=['GET', 'POST'])
def clinic_edit(id):
    patient = Patient.query.get_or_404(id)
    if request.method == 'POST':
        patient.name = request.form['name']
        patient.details = request.form['details']
        patient.weight = float(request.form['weight'])
        patient.age = float(request.form['age'])
        patient.owner_name = request.form['owner_name']
        db.session.commit()
        return redirect('/clinics')
    return render_template('clinic_edit.html', patient=patient)


@clinic.route('/clinic/delete/<int:id>', methods=['POST'])
def clinic_delete(id):
    patient = Patient.query.get_or_404(id)
    db.session.delete(patient)
    db.session.commit()
    return redirect('/clinics')

app/routes/item.py
from flask import Blueprint,  render_template
from models.item_models import Category, Item, Manufacturer
from db import db


item = Blueprint('item', __name__)




@item.route('/items')
def items():
    manufacturers = Manufacturer.query.all()
    return render_template('index.html', manufacturers=manufacturers)

@item.route('/<manufacturer>/categories')
def show_categories(manufacturer):
    manufacturer = Manufacturer.query.filter_by(name=manufacturer).first()
    items = manufacturer.items
    categories = set(item.category for item in items)
    return render_template('categories.html', manufacturer=manufacturer, categories=categories)

@item.route('/<manufacturer>/<category>')
def show_items(manufacturer, category):
    items = Item.query.join(Item.manufacturers).join(Item.category).\
                filter(Manufacturer.name == manufacturer).\
                filter(Category.name == category).all()
    return render_template('items.html', manufacturer=manufacturer, category=category, items=items)

app/routes/main.py
from flask import Blueprint, render_template
from flask_login import login_required, current_user
from models.user_models import Users

main = Blueprint('main', __name__)

@main.route('/')
def index():
    return render_template('index.html')


@main.route('/about')
def about():
    return render_template('about.html')


@main.route('/profile')
@login_required
def profile():
    n = Users.query.order_by(Users.date.desc()).all()
    return render_template('profile.html', name=current_user.name, n=n)

app/routes/post.py
from flask import Blueprint, request, redirect, render_template
from models.post_models import Posts
from db import db


post = Blueprint('post', __name__)


@post.route("/post_add", methods=["POST", "GET"])
def post_add():
    if request.method == 'POST': 
        n = Posts()
        n.title = request.form['title']
        n.intro = request.form['intro']
        n.text = request.form['text']
        try:
            db.session.add(n)
            db.session.commit()
            
            return redirect('/posts')
            
        except:
            return('Ошибка записи') 
    else:      
        return render_template("post_add.html")
    

@post.route("/posts")
def posts():
    n = Posts.query.order_by(Posts.date.desc()).all()
    return render_template("posts.html", n=n)


@post.route("/posts/<int:id>")
def post_datail(id):
    n = Posts.query.get(id)
    return render_template("post_datail.html", n=n)

    
@post.route("/posts/<int:id>/del")
def post_delete(id):
    n = Posts.query.get_or_404(id)

    try:
        db.session.delete(n)
        db.session.commit()
        return redirect('/posts')
    except:
        return "При удалении статьи произошла ошибка"


@post.route("/posts/<int:id>/update", methods=["POST", "GET"]) 
def post_update(id):
    n = Posts.query.get(id)
    if request.method == 'POST': 
        n.title = request.form['title']
        n.intro = request.form['intro']
        n.text = request.form['text']
        try:
            db.session.commit()
            return redirect('/posts') 
        except:
            return "При редактировании статьи произошла ошибка"
         
    else:    
        return render_template("post_update.html", n=n)    

app/routes/song.py
from flask import Blueprint, request, redirect, render_template
from models.song_models import Song
from db import db


song = Blueprint('song', __name__)

@song.route('/songs')
def songs():
    songs_list = Song.query.all()
    return render_template('songs.html', songs=songs_list)

app/routes/super.py
from flask import Blueprint,  render_template, request, redirect
from models.super_models import Grocery
from db import db


super = Blueprint('super', __name__)


@super.route('/supers', methods=['GET'])
def supers():
    groceries = Grocery.query.all()
    return render_template('supers.html', groceries=groceries)

@super.route('/super_add', methods=['GET', 'POST'])
def super_add():
    if request.method == 'POST':
        new_item = Grocery()
        new_item.name = request.form['name']
        new_item.description = request.form['description']
        new_item.weight = request.form['weight']
        new_item.quantity = request.form['quantity']
        new_item.price = request.form['price']
        try:
            db.session.add(new_item)
            db.session.commit()

            return redirect('/supers')
        except:
            return('Ошибка записи') 
    else:      
        return render_template("super_add.html")

app/templates/about.html
{% extends 'base.html' %}

{% block title %}Мое резюме{% endblock %}

{% block content %}
    <div class="container my-5">
        <h1 class="text-center mb-4">Мое резюме</h1>
        <div class="row">
            <div class="col-md-6">
                <h2>Образование</h2>
                <h4>Казахский национальный технический университет</h4>
                <p class="mb-0">Бакалавр инженер системотехник</p>
                <p class="text-muted">1991 - 1996</p>
            </div>
            <div class="col-md-6">
                <h2>Опыт работы</h2>
                <h4>Ген.директор - Alrex</h4>
                <p class="mb-0">2000 - н.в.</p>
                <p class="text-muted">- Разработка и поддержка веб-приложений</p>
                <p class="text-muted">- Работа с Python, Flask, HTML/CSS, Python, MySQL, SAS, VBA</p>
            </div>
        </div>
        <div class="row mt-5">
            <div class="col-md-6">
                <h2>Навыки</h2>
                <ul class="list-group">
                    <li class="list-group-item border-0 py-1"><i class="fa fa-cog"></i> Docker</li>
                    <li class="list-group-item border-0 py-1"><i class="fa fa-cog"></i> Nginx</li>
                    <li class="list-group-item border-0 py-1"><i class="fa fa-cog"></i> Flask</li>
                    <li class="list-group-item border-0 py-1"><i class="fa fa-cog"></i> Postgresql</li>
                    <li class="list-group-item border-0 py-1"><i class="fa fa-cog"></i> HTML/CSS</li>
                    <li class="list-group-item border-0 py-1"><i class="fa fa-cog"></i> Python</li>
                    
                    
                </ul>
            </div>
            <div class="col-md-6">
                <h2>Проекты</h2>
                <h4>Веб-приложение экологической системы</h4>
                <p class="text-muted mb-0">- Разработка веб-приложения  с использованием Docker, Nginx, Flask, Postgresql</p>
                <p class="text-muted">- Системный анализ, Архитектура, Серверная часть, Разработка Веб-приложения</p>
                <h4>Блог</h4>
                <p class="text-muted mb-0">- Разработка блога с использованием Docker, Nginx, Flask, Postgresql</p>
                <p class="text-muted">- Системный анализ, Архитектура, Серверная часть, Разработка Веб-приложения</p>
            </div>
        </div>
        <div class="row mt-5">
            <div class="col-md-6">
                <h2>Контакты</h2>
                <p class="mb-0"><i class="fa fa-phone"></i> Телефон: +87074762333</p>
                <p class="mb-0"><i class="fa fa-envelope"></i> Email: Andrey.Tonkovich@gmail.com</p>
                <p class="mb-0"><i class="fa fa-github"> GitHub: <a href="#"></i>example</a></p>
            </div>
            <div class="col-md-6">
                <h2>Языки</h2>
                <ul class="list-group">
                    <li class="list-group-item border-0 py-1"><i class="fa fa-check-circle"></i> Русский (родной)</li>
                </ul>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="UTF-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>{% block title %}{% endblock %}</title>
    <!-- Bootstrap стили -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
    />
    <!-- иконки fontawesome -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
    />
    <!-- кастомные стили -->
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='custom.css') }}"
    />
  </head>
  <body>
    <!-- навигация -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
        <a class="navbar-brand" href="#">Мой личный сайт</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarNav"
          aria-controls="navbarNav"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div
          class="collapse navbar-collapse justify-content-end"
          id="navbarNav"
        >
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('song.songs') }}">Главная</a>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('main.about') }}">Обо мне</a>
            </li>
            {% if current_user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('book.books') }}">Книги</a>
            </li>
            {% endif %} {% if current_user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('item.items') }}"
                >Инвентаризация</a
              >
            </li>
            {% endif %} {% if current_user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('super.supers') }}"
                >Супермаркет</a
              >
            </li>
            {% endif %} {% if current_user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('clinic.clinics') }}"
                >Клиника</a
              >
            </li>
            {% endif %} {% if not current_user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('auth.login') }}"
                >Авторизация</a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('auth.signup') }}"
                >Регистрация</a
              >
            </li>
            {% endif %} {% if current_user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('auth.logout') }}">Выход</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>

    <!-- контент дочерних шаблонов -->
    <div class="container my-3">{% block content %} {% endblock %}</div>
  </body>
</html>

app/templates/base_book.html
<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="UTF-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>{% block title %}{% endblock %}</title>
    <!-- Bootstrap стили -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
    />
    <!-- иконки fontawesome -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
    />
    <!-- кастомные стили -->
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='custom.css') }}"
    />
  </head>
  <body>
    <!-- навигация -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
        <a class="navbar-brand" href="#">Мои книги</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarNav"
          aria-controls="navbarNav"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div
          class="collapse navbar-collapse justify-content-end"
          id="navbarNav"
        >
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="#">Главная</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Обо мне</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <!-- контент дочерних шаблонов -->
    <div class="container my-3">{% block content %} {% endblock %}</div>
  </body>
</html>

app/templates/base_item.html
<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="UTF-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>{% block title %}{% endblock %}</title>
    <!-- Bootstrap стили -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
    />
    <!-- иконки fontawesome -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
    />
    <!-- кастомные стили -->
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='custom.css') }}"
    />
  </head>
  <body>
    <!-- навигация -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
        <a class="navbar-brand" href="#">Онлайн-магазин ElectronX</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarNav"
          aria-controls="navbarNav"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div
          class="collapse navbar-collapse justify-content-end"
          id="navbarNav"
        >
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="#">Скидки</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Акции</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('song.songs') }}"
                >Выход из инветаризации</a
              >
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <!-- контент дочерних шаблонов -->
    <div class="container my-3">{% block content %} {% endblock %}</div>
  </body>
</html>

app/templates/base_super.html
<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="UTF-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>{% block title %}{% endblock %}</title>
    <!-- Bootstrap стили -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
    />
    <!-- иконки fontawesome -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
    />
    <!-- кастомные стили -->
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='custom.css') }}"
    />
  </head>
  <body>
    <!-- навигация -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
        <a class="navbar-brand" href="#">Товары на складе</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarNav"
          aria-controls="navbarNav"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div
          class="collapse navbar-collapse justify-content-end"
          id="navbarNav"
        >
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="#">Скидки</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Акции</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('song.songs') }}"
                >Выход из Супермаркета</a
              >
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <!-- контент дочерних шаблонов -->
    <div class="container my-3">{% block content %} {% endblock %}</div>
  </body>
</html>

app/templates/book.html
{% extends 'base.html' %} {% block title %}{{ book.title }}{% endblock %} {%
block content %}
<div class="card">
  <div class="card-body">
    <h5 class="card-title">{{ book.title }}</h5>
    <h6 class="card-subtitle mb-2 text-muted">{{ book.author }}</h6>
    <p class="card-text">{{ book.description }}</p>
    <a href="/books" class="btn btn-secondary">&larr; Назад</a>
  </div>
</div>
{% endblock %}

app/templates/books.html
{% extends 'base.html' %} {% block title %}Классические романы{% endblock %} {%
block content %}
<div class="row">
  {% for book in books %}
  <div class="col-sm-6 col-md-4 col-lg-3 mb-4">
    <div class="card">
      <div style="position: relative">
        <div class="card-body" style="min-height: 230px">
          <h5 class="card-title">{{ book.title }}</h5>
          <h6 class="card-subtitle mb-2 text-muted">{{ book.author }}</h6>
          <div class="card-text">{{ book.description[:50] }}...</div>
          <a
            href="/book_detail/{{book.id}}"
            class="btn btn-primary"
            style="position: absolute; bottom: 15px; right: 15px"
            >Подробнее</a
          >
        </div>
      </div>
    </div>
  </div>
  {% endfor %}
</div>
{% endblock %}

app/templates/categories.html
{% extends 'base_item.html' %} {% block title %}{{ manufacturer.name }}
Категории{% endblock %} {% block content %}
<div class="row">
  <div class="col-md-8 offset-md-2">
    <h1 class="my-4">Все товары производителя {{ manufacturer.name }}</h1>
    <ul class="list-group">
      {% for category in categories %}
      <li class="list-group-item">
        <a href="/{{ manufacturer.name }}/{{ category.name }}"
          >{{ category.name }}</a
        >
      </li>
      {% endfor %}
    </ul>
  </div>
</div>
{% endblock %}

app/templates/clinic_edit.html
{% extends 'base_clinic.html' %} {% block content %}
<h1>Редактирование профиля</h1>
<div class="col-6">
  <form
    method="post"
    action="{{ url_for('clinic.clinic_edit', id=patient.id) }}"
  >
    <div class="mb-3">
      <label for="name" class="form-label">Кличка</label>
      <input
        type="text"
        class="form-control"
        id="name"
        name="name"
        value="{{ patient.name }}"
        required
      />
    </div>
    <div class="mb-3">
      <label for="details" class="form-label">Подробности</label>
      <textarea
        class="form-control"
        id="details"
        name="details"
        rows="3"
        required
      >
{{ patient.details }}</textarea
      >
    </div>
    <div class="mb-3">
      <label for="weight" class="form-label">Вес</label>
      <input
        type="text"
        class="form-control"
        id="weight"
        name="weight"
        value="{{ patient.weight }}"
        required
      />
    </div>
    <div class="mb-3">
      <label for="age" class="form-label">Возраст</label>
      <input
        type="text"
        class="form-control"
        id="age"
        name="age"
        value="{{ patient.age }}"
        required
      />
    </div>
    <div class="mb-3">
      <label for="owner_name" class="form-label">Имя и адрес владельца</label>
      <input
        type="text"
        class="form-control"
        id="owner_name"
        name="owner_name"
        value="{{ patient.owner_name }}"
        required
      />
    </div>
    <button type="submit" class="btn btn-primary">Сохранить</button>
  </form>
</div>
{% endblock %}

app/templates/index.html
{% extends 'base_item.html' %} {% block title %}Список производителей{% endblock
%} {% block content %}
<h1 class="my-4">Все производители</h1>
<div class="list-group col-5">
  {% for manufacturer in manufacturers %}
  <a
    href="/{{ manufacturer.name }}/categories"
    class="list-group-item list-group-item-action"
    >{{ manufacturer.name }}</a
  >
  {% endfor %}
</div>
{% endblock %}

app/templates/items.html
{% extends 'base_item.html' %} {% block title %}{{ manufacturer }} - {{ category
}}{% endblock %} {% block content %}
<div class="row">
  <div class="col-md-8 offset-md-2">
    <h1 class="my-4">{{ manufacturer }} - {{ category }}</h1>
    <ul class="list-group">
      {% for item in items %}
      <li class="list-group-item">
        <div class="row">
          <div class="col-md-8">
            <h5>{{ item.name }}</h5>
            <p>{{ item.description }}</p>
          </div>
          <div class="col-md-4">
            <p class="text-end">
              Цена: {{ item.price }} руб., в наличии: {{ item.quantity }} шт.
            </p>
          </div>
        </div>
      </li>
      {% endfor %}
    </ul>
  </div>
</div>
{% endblock %}

app/templates/post_update.html
{% extends 'boot.html' %}

{% block content %}
<h1>{% block title %} Редактирование {% endblock %}</h1>

<form method="post">
    <div class="field">
        <div class="control">
        <label for="intro">Заголовок</label>
        <textarea name="title" placeholder="Заголовок"
                  class="form-control">{{ request.form['title'] or n['title'] }}</textarea>
        </div>
    </div>
    

    <div class="field">
        <div class="control">
        <label for="intro">Анонс</label>
        <textarea name="intro" placeholder="Анонс"
                  class="form-control">{{ request.form['intro'] or n['intro'] }}</textarea>
        </div>
    </div>

    <div class="field">
        <div class="control">
            <label for="text">Статья</label>
            <textarea name="text" placeholder="Статья"
                      class="form-control">{{ request.form['text'] or n['text'] }}</textarea>
        </div>
    </div>
    <div class="field">
        <div class="control">
        <button type="submit" class="btn btn-success">Сохранить</button>
        </div>
    </div>
</form>
<hr>
{% endblock %}

<form method="POST" >
    
    <div class="field">
        <div class="control">
            <input class="input is-large" type="text" name="intro" placeholder="Краткое содержание" autofocus="">
        </div>
    </div>
    <div class="field">
        <div class="control">
            <input class="input is-large" type="text" name="text" placeholder="Текст статьи" autofocus="">
        </div>
    </div>
    <button class="button is-block is-info is-large is-fullwidth">Сохранить</button>
    
</form>

app/templates/signup.html
{% extends "base.html" %} {% block content %}
<div class="column is-4 is-offset-4">
  <h3 class="title">Регистрация</h3>
  <div class="box">
    {% with messages = get_flashed_messages() %} {% if messages %}
    <div class="notification is-danger">
      {{ messages[0] }}. Go to
      <a href="{{ url_for('auth.login') }}">login page</a>.
    </div>
    {% endif %} {% endwith %}
    <form method="POST" action="/signup" class="form-horizontal">
      <div class="form-group">
        <label for="inputEmail" class="control-label col-xs-2">Email</label>
        <div class="col-xs-10">
          <input
            class="input is-large"
            type="email"
            name="email"
            placeholder="Ваш Email"
            autofocus=""
          />
        </div>
      </div>

      <div class="form-group">
        <label for="inputname" class="control-label col-xs-2">Имя</label>
        <div class="col-xs-10">
          <input
            class="input is-large"
            type="text"
            name="name"
            placeholder="Ваше имя"
            autofocus=""
          />
        </div>
      </div>

      <div class="form-group">
        <label for="inputpassword" class="control-label col-xs-2">Пароль</label>
        <div class="col-xs-10">
          <input
            class="input is-large"
            type="password"
            name="password"
            placeholder="Пароль"
          />
        </div>
      </div>

      <div class="form-group">
        <label for="inputpassword2" class="control-label col-xs-2"
          >Пароль</label
        >
        <div class="col-xs-10">
          <input
            class="input is-large"
            type="password"
            name="password2"
            placeholder="Повторить пароль"
          />
        </div>
      </div>

      <div class="form-group">
        <div class="col-xs-offset-2 col-xs-10">
          <button type="submit" class="btn btn-primary">Регистрация</button>
        </div>
      </div>
    </form>
  </div>
</div>
{% endblock %}

app/templates/songs.html
{% extends 'base.html' %} {% block title %} Мои любимые песни {% endblock %} {%
block content %}
<h1 class="mb-5">Мои любимые песни</h1>

<div class="card-columns">
  <div class="row">
    {% for song in songs %}
    <div class="col-md-3">
      <div class="card mb-3">
        <div class="card-header fw-bold">{{ song.title }}</div>
        <div class="card-body">
          <p class="badge bg-primary text-wrap">{{ song.album.artist.name }}</p>
          <p class="card-text">
            Альбом: <strong>{{ song.album.title }}</strong>
          </p>
          <p class="card-text">Длина: {{ song.length }} минут</p>
          <p class="card-text">Номер трека: {{ song.track_number }}</p>
          <p class="card-text">Дата релиза: {{ song.album.year }}</p>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>

{% endblock %}